### PR TITLE
fix(server): use interface{} for store handler swag annotations

### PR DESCRIPTION
**Pull request by yamoyamoto**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [x] I have added relevant tests.
- [x] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary

`Build-Images-Push-Docker` on `main` fails at `make swag` since #8854:

https://github.com/apache/incubator-devlake/actions/runs/24995058459
```
ParseComment error in file /app/server/api/store/store.go :cannot find type definition: json.RawMessage
```

`json.RawMessage` is `encoding/json`'s `[]byte`, so swag treats it as a byte array and emits a schema for an integer array — not what this API actually returns. The correct way to express "any JSON value" in an OpenAPI annotation is `interface{}`, which swag emits as an empty schema (`{}`). This PR replaces the three `json.RawMessage` references in `store.go`'s annotations with `interface{}`. Annotation-only; runtime is unchanged.

### Does this close any open issues?
N/A

### Screenshots
N/A

### CODE REVIEW

**Comment by klesh** [comment]
Nice catch!

**Review by klesh — APPROVED** [review]
